### ISSUE TITLE
后端修改文件/文件夹借口缺失以及删除文件夹出错

### ISSUE THREAD

**Issue by kangbb** [sysu-go-online/service-end#6]
# 后端存在的问题

## 对于文件夹及文件的更改未实现

是否增加，后端考量。

## 删除文件夹失败
1.错误如下：<br/>
vue-resource.esm.js:1082 DELETE http://localhost:8080/api/1/tree/controller 500 (Internal Server Error)<br/>
2. response的信息：<br/>
remove /home/kangbb/Work/go/src/github.com/sysu-go-online/service-end/test/controller: directory not empty

**Comment by TXZdream** [comment]
## 删除文件(夹)
已解决删除问题
## 文件夹的更改
当前暂时不考虑较为复杂的更名问题，可能不算复杂，但暂不考虑
